
export const stock =[
    {id:"01",
     nombre:"Cintas. Mala madre. Chlorophytum Comosum",
    precio:1200,
    descripcion: "Es una planta perenne perteneciente a la familia Agavaceae y originaria de Sudáfrica.Se le conoce popularmente por los nombres de cinta, malamadre, araña o lazo de amor.Es muy utilizada como planta de interior, debido a su fácil cultivo en maceta, pero también puede ubicarse en el exterior en climas cálidos. Es muy resistente, soporta hasta -2 °C.Es de porte colgante, con unas hojas largas y luminosas. Desarrolla en ellas unos estolones y unas diminutas flores de color blanco.Es muy fácil de reproducir y de cuidar.De hecho, es una planta recomendada para principiantes o para aquellos que tengan poca mano con ellas.", 
    foto:"/imagenes/planta.jpg",
    categoria:"interior"
    },
    {id:"02",
     nombre:"Ficus Lyrata. Higuera hoja de violín",
    precio:1150,
    descripcion: "Es una árbol ornamental popular en jardines tropicales y subtropicales, y también se cultiva como planta de interior en áreas templadas, donde por lo general se mantiene más bajo, no florece ni da frutos. Es resistente hasta 10 °C, por lo que un ejemplar puede colocarse en exteriores durante períodos cálidos.Esta planta ha ganado el Galardón al Mérito en Jardinería de la Real Sociedad de Horticultura", 
    foto:"/imagenes/planta4.jpg", 
    categoria:"interior"},
    {id:"03", 
    nombre:"Bambú de la suerte. Dracaena sanderiana",
    precio:1300,
    descripcion: "Es un grupo de pequeños arbustos con tallos delgados y flexibles (similar a una caña) con hojas en forma de cinta que crecen como plantas de sotobosque en las selvas tropicales. Es un arbusto de crecimiento vertical que alcanza los 1,5 m de altura, con hojas de 15 - 25 cm de largo y 1.5-4 cm de ancho en la base.", 
    foto:"/imagenes/planta3.jpg",
     categoria:"interior"},  
    {id:"04",
     nombre:"Palo de Brasil. Palo de Agua. Dracena Deremensis",
    precio:1500,
    descripcion:"Es una planta de hoja perenne originaria de África.Considerada como una planta tropical, sus hojas son largas y colgantes con una pequeña franja amarilla en el medio, mientras que el tronco es grueso y color marrón.El palo de Brasil puede llegar a medir hasta seis metros si se siembra directamente en el suelo, pero es común verlo en interiores también, ya sea en macetas o en las terrazas, con una altura máxima de dos metros.", 
    foto:"/imagenes/planta2.jpg", 
    categoria:"exterior"},
    {id:"05",
     nombre:"Helecho.taxón Filicopsida, Pterophyta",
    precio:1000,
    descripcion:"Los helechos son plantas sin flores ni semillas, pertenecientes al grupo de las Pteridofitas. Se reproducen mediante esporas, las cuales necesitan la presencia de agua para completar su ciclo biológico. Los helechos son notables por: Sus hojas (frondes).", 
    foto:"/imagenes/planta5.jpg", 
    categoria:"exterior"},
    {id:"06",
     nombre:"Cactus. Cactacea. Cacti. Caryophyllales",
    precio:800,
    descripcion:"Es una planta de hoja perenne originaria de África.Considerada como una planta tropical, sus hojas son largas y colgantes con una pequeña franja amarilla en el medio, mientras que el tronco es grueso y color marrón.El palo de Brasil puede llegar a medir hasta seis metros si se siembra directamente en el suelo, pero es común verlo en interiores también, ya sea en macetas o en las terrazas, con una altura máxima de dos metros.", 
    foto:"/imagenes/planta6.jpg", 
    categoria:"exterior"},
    {id:"07",
     nombre:"Maceta exterior",
    precio:700,
    descripcion:"Estas deben ser pensadas para el correcto drenaje del agua, puesto que, generalmente se colocan en lugares sin techo y sin protección de la lluvia. Las macetas tienen orificios en la parte de abajo para controlar la humedad. Un material ideal para las macetas de exterior son las elaboradas en barro.", 
    foto:"/imagenes/maceta1.jpg", 
    categoria:"macetas"},
    {id:"08",
     nombre:"Maceta interior",
    precio:500,
    descripcion:"Seleccionar macetas para interiores es más sencillo porque la temperatura es más estable. Sin embargo, aún en el interior, no se debe dejar una planta sin supervisión  y sin agua. ¡Te recomendamos agregar el cuidado de las plantas en tu listado de tareas del hogar! ", 
    foto:"/imagenes/maceta2.jpg", 
    categoria:"macetas"},
    {id:"09",
     nombre:"Maceta para  Bonsai" ,
    precio:1500,
    descripcion:"Seleccionar macetas para interiores es más sencillo porque la temperatura es más estable. Sin embargo, aún en el interior, no se debe dejar una planta sin supervisión  y sin agua. ¡Te recomendamos agregar el cuidado de las plantas en tu listado de tareas del hogar! ", 
    foto:"/imagenes/maceta3.jpg", 
    categoria:"macetas"},
]

